// Predefined option lists used for searchable selects on the admin
// "Trainer Profile" (Add/Edit Trainer) form — location fields and skills.
// Keeping these as flat arrays keeps the SearchableSelect components simple;
// "allowCustom" on those components still lets an admin add a value that
// isn't in these lists (e.g. a smaller town, or a niche skill).

export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi (NCT)",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];

export const INDIAN_CITIES = [
  "Delhi",
  "Noida",
  "Gurgaon",
  "Faridabad",
  "Ghaziabad",
  "Mumbai",
  "Navi Mumbai",
  "Thane",
  "Pune",
  "Bengaluru",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Ahmedabad",
  "Surat",
  "Vadodara",
  "Jaipur",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Indore",
  "Bhopal",
  "Chandigarh",
  "Mohali",
  "Ludhiana",
  "Amritsar",
  "Coimbatore",
  "Kochi",
  "Thiruvananthapuram",
  "Visakhapatnam",
  "Vijayawada",
  "Nashik",
  "Aurangabad",
  "Raipur",
  "Ranchi",
  "Patna",
  "Bhubaneswar",
  "Guwahati",
  "Dehradun",
  "Jodhpur",
  "Udaipur",
  "Mysuru",
  "Mangaluru",
  "Madurai",
  "Trichy",
  "Agra",
  "Varanasi",
  "Meerut",
  "Gwalior",
  "Rajkot",
  "Remote / Pan India",
];

export const IT_SKILLS = [
  "Java",
  "Python",
  "JavaScript",
  "TypeScript",
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "HTML/CSS",
  ".NET",
  "C#",
  "C++",
  "C",
  "Go",
  "PHP",
  "Django",
  "Flask",
  "Spring Boot",
  "AWS",
  "Microsoft Azure",
  "Google Cloud Platform (GCP)",
  "DevOps",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "Terraform",
  "Ansible",
  "Linux",
  "Networking",
  "Cybersecurity",
  "Ethical Hacking",
  "SQL",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Data Science",
  "Machine Learning",
  "Deep Learning",
  "Artificial Intelligence",
  "Generative AI",
  "Big Data",
  "Hadoop",
  "Apache Spark",
  "Power BI",
  "Tableau",
  "Excel",
  "Salesforce",
  "SAP",
  "ServiceNow",
  "Selenium",
  "Manual/Automation Testing",
  "UI/UX Design",
  "Agile/Scrum",
  "PMP",
  "ITIL",
  "Business Analysis",
  "RPA/UiPath",
  "Blockchain",
  "Digital Marketing",
  "Soft Skills",
];
